# Generated by Django 5.1.5 on 2025-02-04 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/thumbnails/'),
        ),
    ]
