# Generated by Django 5.1.5 on 2025-02-06 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={},
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table=None,
        ),
    ]
